### ISSUE TITLE
Entregar primer bot

### ISSUE THREAD

**Issue by aernesto** [aernesto/Lux-Design-S2#5]
Aún con un bot super sencillo, para checar que entendemos como entrar en la competencia.

**Comment by aernesto** [comment]
Logic proposition for first bot: (enhancements for second bot marked as v2)

- Build factories blindly at first available location
- If N is the total number of ice and ore tiles on map, build N heavy robots (as metal & power allows)
    - assign 3000 power per heavy robot; if power not available, cancel build action
    - assign a target resource tile to each robot
- once robot build cannot be performed, systematically water as resource allows.
- each robot makes cycle trips from factory to target resource tile and back. Each turn
    - (v2) check that planned action won't provoke collision with other heavy robot, if it will, wait, if risk still increases, attack (kamikaze)
    - once on resource tile, dig until full
    - once near factory, transfer
- track time evolution of all resources (mine and opponent's)

**Comment by aernesto** [comment]
[done](https://github.com/aernesto/Lux-Design-S2/releases/tag/v1.2)
Listo @AlfonsoOC !

**Comment by AlfonsoOC** [comment]
Yuhuuuuuuuuu!!!
